// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    public class UpdateConstantMovementsHandler {
        
        public ContinuousMovement Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrame.ECS.EcsComponent Vector3Library_component = default( uFrame.ECS.EcsComponent );
        
        private UnityEngine.Vector3 Vector3Library_direction = default( UnityEngine.Vector3 );
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // Before visit uFrame.Actions.Vector3Library.TranslateWithTime
            Vector3Library_component = Group;
            Vector3Library_direction = Group.Direction;
            // Visit uFrame.Actions.Vector3Library.TranslateWithTime
            while (this.DebugInfo("65a226dc-3c7e-461b-a697-6d9e26c1fb5c", this) == 1) yield return new WaitForEndOfFrame();
            uFrame.Actions.Vector3Library.TranslateWithTime(Vector3Library_component, Vector3Library_direction);
            // HANDLER: UpdateConstantMovements
            yield break;
        }
    }
}
