// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public partial class InputSystem : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemUpdate {
        
        private IEcsComponentManagerOf<Movable> _MovableManager;
        
        public IEcsComponentManagerOf<Movable> MovableManager {
            get {
                return _MovableManager;
            }
            set {
                _MovableManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MovableManager = ComponentSystem.RegisterComponent<Movable>();
        }
        
        protected void HandleMovementInputHandler(Movable group) {
            var handler = new HandleMovementInputHandler();
            handler.System = this;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void HandleMovementInputFilter() {
            var MovableItems = MovableManager.Components.GetEnumerator();
            for (
            ; MovableItems.MoveNext(); 
            ) {
                this.HandleMovementInputHandler(MovableItems.Current);
            }
        }
        
        public virtual void SystemUpdate() {
            HandleMovementInputFilter();
        }
    }
}
