// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class SpawnMultipleAtIntervalComponentCreated {
        
        public SpawnMultipleAtInterval Group;
        
        private SpawnMultipleAtInterval _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject GetRandomListItem24_Result = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode25_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode25_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode25_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode25_Result = default( UnityEngine.GameObject );
        
        public SpawnMultipleAtInterval Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // GetRandomListItem
            GetRandomListItem24_Result = Group.Items[UnityEngine.Random.Range(0, Group.Items.Count)];
            ActionNode25_gameObject = GetRandomListItem24_Result;
            // ActionNode
            // Visit uFrame.Actions.GameObjects.Instantiate
            ActionNode25_Result = uFrame.Actions.GameObjects.Instantiate(ActionNode25_gameObject, ActionNode25_position, ActionNode25_rotation);
            // SetVariableNode
            ActionNode25_Result.transform.parent = (UnityEngine.Transform)Group.Parent;
        }
    }
}
