// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class RandomRotationComponentCreated {
        
        public RandomRotation Group;
        
        private RandomRotation _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode10_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode10_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode10_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode13_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode12_a = default( UnityEngine.Vector3 );
        
        private float ActionNode12_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode12_Result = default( UnityEngine.Vector3 );
        
        public RandomRotation Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode10_go = Group.Entity.gameObject;
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            while (this.DebugInfo("b1e4431f-e657-45d8-8679-5b5dd0f12a26","d10f965c-838c-4db4-80f0-a1bb93be8617", this) == 1) yield return null;
            ActionNode10_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode10_go, ActionNode10_component);
            // Visit uFrame.Actions.CreateRandoms.GetInsideSphere
            while (this.DebugInfo("d10f965c-838c-4db4-80f0-a1bb93be8617","4a39023b-ffca-44b7-be0c-a2aff7e62f51", this) == 1) yield return null;
            ActionNode13_Result = uFrame.Actions.CreateRandoms.GetInsideSphere();
            ActionNode12_a = ActionNode13_Result;
            ActionNode12_b = Group.Tumble;
            // Visit uFrame.Actions.Vector3Library.Multiply
            while (this.DebugInfo("4a39023b-ffca-44b7-be0c-a2aff7e62f51","f8756661-d8ca-4745-9575-a1d546e7f049", this) == 1) yield return null;
            ActionNode12_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode12_a, ActionNode12_b);
            while (this.DebugInfo("f8756661-d8ca-4745-9575-a1d546e7f049","2cb1c689-05ea-48d4-bb80-f2a049c384b3", this) == 1) yield return null;
            ActionNode10_Result.angularVelocity = (UnityEngine.Vector3)ActionNode12_Result;
            // HANDLER: BeginRandomRotation
            yield break;
        }
    }
}
