// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    using uFrame.ECS;
    
    
    public class BeginMultipleIntervalSpawnComponentCreated {
        
        public SpawnMultipleAtInterval Group;
        
        private SpawnMultipleAtInterval _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private float ActionNode22_Seconds = default( System.Single );
        
        private uFrame.ECS.IEcsComponent ActionNode22_DisposeWith = default( uFrame.ECS.IEcsComponent );
        
        private uFrame.Actions.IntervalBySeconds ActionNode22 = new uFrame.Actions.IntervalBySeconds();
        
        private System.IDisposable ActionNode22_Result = default( System.IDisposable );
        
        private UnityEngine.GameObject GetRandomListItem8_Result = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode2_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode2_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode2_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode2_Result = default( UnityEngine.GameObject );
        
        public SpawnMultipleAtInterval Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode22_Seconds = Group.SpawnSpeed;
            ActionNode22_DisposeWith = Group;
            // ActionNode
            while (this.DebugInfo("7acc43ed-c009-4cf2-9b24-6035e784d2b8","bfcf80a6-3eed-4be7-bb0b-4c6430ceae1d", this) == 1) yield return null;
            // Visit uFrame.Actions.IntervalBySeconds
            ActionNode22.Seconds = ActionNode22_Seconds;
            ActionNode22.DisposeWith = ActionNode22_DisposeWith;
            ActionNode22.System = System;
            ActionNode22.Tick = ()=> { System.StartCoroutine(ActionNode22_Tick()); };
            ActionNode22.Execute();
            ActionNode22_Result = ActionNode22.Result;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode22_Tick() {
            ActionNode22_Result = ActionNode22.Result;
            // GetRandomListItem
            while (this.DebugInfo("bfcf80a6-3eed-4be7-bb0b-4c6430ceae1d","d7539db4-c189-4b19-b1e7-1fe76bf2b20f", this) == 1) yield return null;
            GetRandomListItem8_Result = Group.Items[UnityEngine.Random.Range(0, Group.Items.Count)];
            ActionNode2_gameObject = GetRandomListItem8_Result;
            // ActionNode
            while (this.DebugInfo("d7539db4-c189-4b19-b1e7-1fe76bf2b20f","bb15b38a-b946-4b9a-b438-390cd2d9194c", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.Instantiate
            ActionNode2_Result = uFrame.Actions.GameObjects.Instantiate(ActionNode2_gameObject, ActionNode2_position, ActionNode2_rotation);
            // SetVariableNode
            while (this.DebugInfo("bb15b38a-b946-4b9a-b438-390cd2d9194c","42976861-8c91-41e7-9188-a0de2f8a460d", this) == 1) yield return null;
            ActionNode2_Result.transform.parent = (UnityEngine.Transform)Group.Parent;
            yield break;
        }
    }
}
