// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class RandomRotationComponentCreated {
        
        public RandomRotation Group;
        
        private RandomRotation _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode10_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode10_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode10_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode13_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode12_a = default( UnityEngine.Vector3 );
        
        private float ActionNode12_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode12_Result = default( UnityEngine.Vector3 );
        
        public RandomRotation Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode10_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            ActionNode10_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode10_go, ActionNode10_component);
            // ActionNode
            // Visit uFrame.Actions.CreateRandoms.GetInsideSphere
            ActionNode13_Result = uFrame.Actions.CreateRandoms.GetInsideSphere();
            ActionNode12_a = ActionNode13_Result;
            ActionNode12_b = Group.Tumble;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Multiply
            ActionNode12_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode12_a, ActionNode12_b);
            // SetVariableNode
            ActionNode10_Result.angularVelocity = (UnityEngine.Vector3)ActionNode12_Result;
        }
    }
}
