// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DestroyOnCollisionHandler {
        
        public DestroyOnCollision EntityId;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode17_entityId = default( System.Int32 );
        
        private float ActionNode17_time = default( System.Single );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode17_entityId = EntityId.EntityId;
            // ActionNode
            // Visit uFrame.Actions.DestroyLibrary.DestroyEntity
            uFrame.Actions.DestroyLibrary.DestroyEntity(ActionNode17_entityId, ActionNode17_time);
        }
    }
}
