// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class WavesGameComponentDestroyed {
        
        public WavesGame Group;
        
        private WavesGame _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.MenuUI LoopGroupNode35_Item = default( uFrameECSDemo.MenuUI );
        
        private UnityEngine.GameObject ActionNode36_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode36_behaviour = default( UnityEngine.MonoBehaviour );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // LoopGroupNode
            while (this.DebugInfo("3f32177f-f20b-4ec8-834a-be40e1c82207","43bc328b-e53e-4807-84ab-5665716468c7", this) == 1) yield return null;
            var LoopGroupNode35_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSDemo.MenuUI>().Components;
            for (var LoopGroupNode35_ItemIndex = 0
            ; LoopGroupNode35_ItemIndex < LoopGroupNode35_GroupComponents.Count; LoopGroupNode35_ItemIndex++
            ) {
                LoopGroupNode35_Item = LoopGroupNode35_GroupComponents[LoopGroupNode35_ItemIndex];
                System.StartCoroutine(LoopGroupNode35_Next());
            }
            yield break;
        }
        
        private System.Collections.IEnumerator LoopGroupNode35_Next() {
            ActionNode36_gameObject = LoopGroupNode35_Item.gameObject;
            // ActionNode
            while (this.DebugInfo("43bc328b-e53e-4807-84ab-5665716468c7","d86d476a-60a8-46bf-b1e1-90583786c467", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.ActivateGameObject
            uFrame.Actions.GameObjects.ActivateGameObject(ActionNode36_gameObject, ActionNode36_behaviour);
            yield break;
        }
    }
}
