// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UnityEngine;
    
    
    public class WavesGameComponentDestroyed {
        
        public WavesGame Group;
        
        private WavesGame _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.MenuUI LoopGroupNode35_Item = default( uFrameECSDemo.MenuUI );
        
        private UnityEngine.GameObject ActionNode36_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode36_behaviour = default( UnityEngine.MonoBehaviour );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode35_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSDemo.MenuUI>().Components;
            for (var LoopGroupNode35_ItemIndex = 0
            ; LoopGroupNode35_ItemIndex < LoopGroupNode35_GroupComponents.Count; LoopGroupNode35_ItemIndex++
            ) {
                LoopGroupNode35_Item = LoopGroupNode35_GroupComponents[LoopGroupNode35_ItemIndex];
                LoopGroupNode35_Next();
            }
        }
        
        private void LoopGroupNode35_Next() {
            ActionNode36_gameObject = LoopGroupNode35_Item.gameObject;
            // ActionNode
            // Visit uFrame.Actions.GameObjects.ActivateGameObject
            uFrame.Actions.GameObjects.ActivateGameObject(ActionNode36_gameObject, ActionNode36_behaviour);
        }
    }
}
