// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    using uFrameECSDemo;
    
    
    public class EnemyAISystemFixedUpdateHandler {
        
        public EnemyAI Group;
        
        private uFrame.ECS.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.EnemyAI ActionNode18_EnemyAI = default( uFrameECSDemo.EnemyAI );
        
        private uFrameECSDemo.EnemyAIFixedUpdate ActionNode18 = new uFrameECSDemo.EnemyAIFixedUpdate();
        
        public uFrame.ECS.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode18_EnemyAI = Group;
            // ActionNode
            while (this.DebugInfo("03db7d7e-7273-499f-b530-127999b3f37c","1cb0d40e-31a3-4596-a7de-190c9ccf1b55", this) == 1) yield return null;
            // Visit uFrameECSDemo.EnemyAIFixedUpdate
            ActionNode18.EnemyAI = ActionNode18_EnemyAI;
            ActionNode18.System = System;
            ActionNode18.Execute();
            yield break;
        }
    }
}
