// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    using uFrameECSDemo;
    
    
    public class EnemyAICreatedComponentCreated {
        
        public EnemyAI Group;
        
        private EnemyAI _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.EnemyAI ActionNode17_EnemyAI = default( uFrameECSDemo.EnemyAI );
        
        private uFrameECSDemo.EnemyAIStart ActionNode17 = new uFrameECSDemo.EnemyAIStart();
        
        public EnemyAI Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode17_EnemyAI = Group;
            // ActionNode
            while (this.DebugInfo("5d9e6255-926d-40e7-b316-d63686ca222f","4b51f9c4-2bcd-4a95-b50d-65d0889fdff6", this) == 1) yield return null;
            // Visit uFrameECSDemo.EnemyAIStart
            ActionNode17.EnemyAI = ActionNode17_EnemyAI;
            ActionNode17.System = System;
            ActionNode17.Execute();
            yield break;
        }
    }
}
