// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public class GrabStartPosition {
        
        public BackgroundScroller Group;
        
        private BackgroundScroller _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        public BackgroundScroller Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // SetVariableNode
            while (this.DebugInfo("05e35c80-2017-4041-9947-42cebdc7b7b3","b1e4431f-e657-45d8-8679-5b5dd0f12a26", this) == 1) yield return null;
            Group.StartPosition = (UnityEngine.Vector3)Group.Entity.transform.position;
            yield break;
        }
    }
}
