// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class BackgroundScrollerComponentCreated {
        
        public BackgroundScroller Group;
        
        private BackgroundScroller _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        public BackgroundScroller Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            Group.StartPosition = (UnityEngine.Vector3)Group.Entity.transform.position;
            // HANDLER: GrabStartPosition
            yield break;
        }
    }
}
