// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GunnerInputUpdateHandler {
        
        public LocalGunner Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.KeyCode ActionNode50_key = default( UnityEngine.KeyCode );
        
        private UnityEngine.KeyCode EnumValueNode1 = KeyCode.Space;
        
        private bool ActionNode50_Result = default( System.Boolean );
        
        private uFrameECSDemo.Gun LoopCollectionNode5_Item = default( uFrameECSDemo.Gun );
        
        private uFrameECSDemo.GunState EnumValueNode10 = GunState.Shooting;
        
        private UnityEngine.KeyCode ActionNode60_key = default( UnityEngine.KeyCode );
        
        private bool ActionNode60_Result = default( System.Boolean );
        
        private uFrameECSDemo.Gun LoopCollectionNode6_Item = default( uFrameECSDemo.Gun );
        
        private uFrameECSDemo.GunState EnumValueNode9 = GunState.Idle;
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode50_key = EnumValueNode1;
            // ActionNode
            // Visit uFrame.Actions.InputLibrary.IsKeyDown
            ActionNode50_Result = uFrame.Actions.InputLibrary.IsKeyDown(ActionNode50_key, ActionNode50_yes, ActionNode50_no);
            ActionNode60_key = EnumValueNode1;
            // ActionNode
            // Visit uFrame.Actions.InputLibrary.IsKeyUp
            ActionNode60_Result = uFrame.Actions.InputLibrary.IsKeyUp(ActionNode60_key, ActionNode60_yes, ActionNode60_no);
        }
        
        private void LoopCollectionNode5_Next() {
            // SetVariableNode
            LoopCollectionNode5_Item.State = (uFrameECSDemo.GunState)EnumValueNode10;
        }
        
        private void ActionNode50_yes() {
            // LoopCollectionNode
            for (var LoopCollectionNode5_ItemIndex = 0
            ; LoopCollectionNode5_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode5_ItemIndex++
            ) {
                LoopCollectionNode5_Item = Group.Gunner.Guns[LoopCollectionNode5_ItemIndex];
                LoopCollectionNode5_Next();
            }
        }
        
        private void ActionNode50_no() {
        }
        
        private void LoopCollectionNode6_Next() {
            // SetVariableNode
            LoopCollectionNode6_Item.State = (uFrameECSDemo.GunState)EnumValueNode9;
        }
        
        private void ActionNode60_yes() {
            // LoopCollectionNode
            for (var LoopCollectionNode6_ItemIndex = 0
            ; LoopCollectionNode6_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode6_ItemIndex++
            ) {
                LoopCollectionNode6_Item = Group.Gunner.Guns[LoopCollectionNode6_ItemIndex];
                LoopCollectionNode6_Next();
            }
        }
        
        private void ActionNode60_no() {
        }
    }
}
