// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class GunnerInputUpdateHandler {
        
        public PlayerGunner Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.KeyCode ActionNode3_key = default( UnityEngine.KeyCode );
        
        private UnityEngine.KeyCode EnumValueNode1 = KeyCode.Space;
        
        private bool ActionNode3_Result = default( System.Boolean );
        
        private uFrameECSDemo.Gun LoopCollectionNode11_Item = default( uFrameECSDemo.Gun );
        
        private uFrameECSDemo.GunState EnumValueNode10 = GunState.Shooting;
        
        private uFrameECSDemo.Gun LoopCollectionNode10_Item = default( uFrameECSDemo.Gun );
        
        private uFrameECSDemo.GunState EnumValueNode9 = GunState.Idle;
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode3_key = EnumValueNode1;
            // ActionNode
            // Visit uFrame.Actions.InputLibrary.IsKeyDown
            ActionNode3_Result = uFrame.Actions.InputLibrary.IsKeyDown(ActionNode3_key, ActionNode3_yes, ActionNode3_no);
        }
        
        private void LoopCollectionNode11_Next() {
            // SetVariableNode
            LoopCollectionNode11_Item.State = (uFrameECSDemo.GunState)EnumValueNode10;
        }
        
        private void ActionNode3_yes() {
            // LoopCollectionNode
            for (var LoopCollectionNode11_ItemIndex = 0
            ; LoopCollectionNode11_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode11_ItemIndex++
            ) {
                LoopCollectionNode11_Item = Group.Gunner.Guns[LoopCollectionNode11_ItemIndex];
                LoopCollectionNode11_Next();
            }
        }
        
        private void LoopCollectionNode10_Next() {
            // SetVariableNode
            LoopCollectionNode10_Item.State = (uFrameECSDemo.GunState)EnumValueNode9;
        }
        
        private void ActionNode3_no() {
            // LoopCollectionNode
            for (var LoopCollectionNode10_ItemIndex = 0
            ; LoopCollectionNode10_ItemIndex < Group.Gunner.Guns.Count; LoopCollectionNode10_ItemIndex++
            ) {
                LoopCollectionNode10_Item = Group.Gunner.Guns[LoopCollectionNode10_ItemIndex];
                LoopCollectionNode10_Next();
            }
        }
    }
}
