// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UnityEngine;
    
    
    public class PointsOnDestroyComponentDestroyed {
        
        public PointsOnDestroy Group;
        
        private PointsOnDestroy _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.WavesGame LoopGroupNode10_Item = default( uFrameECSDemo.WavesGame );
        
        private int ActionNode0_a = default( System.Int32 );
        
        private int ActionNode0_b = default( System.Int32 );
        
        private int ActionNode0_Result = default( System.Int32 );
        
        public PointsOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode10_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSDemo.WavesGame>().Components;
            for (var LoopGroupNode10_ItemIndex = 0
            ; LoopGroupNode10_ItemIndex < LoopGroupNode10_GroupComponents.Count; LoopGroupNode10_ItemIndex++
            ) {
                LoopGroupNode10_Item = LoopGroupNode10_GroupComponents[LoopGroupNode10_ItemIndex];
                LoopGroupNode10_Next();
            }
        }
        
        private void LoopGroupNode10_Next() {
            ActionNode0_a = LoopGroupNode10_Item.Score;
            ActionNode0_b = Group.Points;
            // ActionNode
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode0_Result = uFrame.Actions.IntLibrary.Add(ActionNode0_a, ActionNode0_b);
            // SetVariableNode
            LoopGroupNode10_Item.Score = (System.Int32)ActionNode0_Result;
        }
    }
}
