// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class EffectOnDestroyComponentDestroyed {
        
        public EffectOnDestroy Group;
        
        private EffectOnDestroy _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode5_value = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode6_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode6_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode6_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode6_Result = default( UnityEngine.GameObject );
        
        public EffectOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode5_value = Group.IsQuiting;
            // ActionNode
            while (this.DebugInfo("28b81b2d-3039-4b03-9424-6fb8bb4421d6","769f512b-3bbf-40d3-9e31-e3ef5572cefe", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode5_value, ()=> { System.StartCoroutine(ActionNode5_yes()); }, ()=> { System.StartCoroutine(ActionNode5_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode5_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode5_no() {
            ActionNode6_gameObject = Group.Prefab;
            ActionNode6_position = Group.transform.position;
            // ActionNode
            while (this.DebugInfo("769f512b-3bbf-40d3-9e31-e3ef5572cefe","115892cd-156e-4117-8ccc-264b5a8ed3d4", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.Instantiate
            ActionNode6_Result = uFrame.Actions.GameObjects.Instantiate(ActionNode6_gameObject, ActionNode6_position, ActionNode6_rotation);
            yield break;
        }
    }
}
