// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public class PlayerGunnerComponentDestroyed {
        
        public PlayerGunner Group;
        
        private PlayerGunner _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.GameOver PublishEventNode19_Result = default( uFrameECSDemo.GameOver );
        
        public PlayerGunner Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("5ab1ad6f-a0f5-4cdb-9b19-dd9f26edcb86","3f32177f-f20b-4ec8-834a-be40e1c82207", this) == 1) yield return null;
            var PublishEventNode19_Event = new GameOver();
            System.Publish(PublishEventNode19_Event);
            PublishEventNode19_Result = PublishEventNode19_Event;
            yield break;
        }
    }
}
