// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public class PlayerSystemOnCollisionEnterHandler {
        
        public Hazard Collider;
        
        public PlayerGunner Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode17_gameObject = default( UnityEngine.GameObject );
        
        private float ActionNode17_time = default( System.Single );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode17_gameObject = Collider.Entity.gameObject;
            // ActionNode
            while (this.DebugInfo("12fae0e0-3723-4d36-9b84-c418fd17e038","2bcd91d8-c24c-43df-8642-01a955e20a81", this) == 1) yield return null;
            // Visit uFrame.Actions.DestroyLibrary.DestroyGameObject
            uFrame.Actions.DestroyLibrary.DestroyGameObject(ActionNode17_gameObject, ActionNode17_time);
            yield break;
        }
    }
}
