// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PointsOnDestroyComponentDestroyed {
        
        public PointsOnDestroy Group;
        
        private PointsOnDestroy _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.WavesGame LoopGroupNode32_Item = default( uFrameECSDemo.WavesGame );
        
        private int ActionNode33_a = default( System.Int32 );
        
        private int ActionNode33_b = default( System.Int32 );
        
        private int ActionNode33_Result = default( System.Int32 );
        
        public PointsOnDestroy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode32_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSDemo.WavesGame>().Components;
            for (var LoopGroupNode32_ItemIndex = 0
            ; LoopGroupNode32_ItemIndex < LoopGroupNode32_GroupComponents.Count; LoopGroupNode32_ItemIndex++
            ) {
                LoopGroupNode32_Item = LoopGroupNode32_GroupComponents[LoopGroupNode32_ItemIndex];
                LoopGroupNode32_Next();
            }
        }
        
        private void LoopGroupNode32_Next() {
            ActionNode33_a = LoopGroupNode32_Item.Score;
            ActionNode33_b = Group.Points;
            // ActionNode
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode33_Result = uFrame.Actions.IntLibrary.Add(ActionNode33_a, ActionNode33_b);
            // SetVariableNode
            LoopGroupNode32_Item.Score = (System.Int32)ActionNode33_Result;
        }
    }
}
