// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ProjectileCreated {
        
        public Projectile Group;
        
        private Projectile _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode3_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode3_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode3_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode1_a = default( UnityEngine.Vector3 );
        
        private float ActionNode1_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode1_Result = default( UnityEngine.Vector3 );
        
        public Projectile Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode3_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            ActionNode3_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode3_go, ActionNode3_component);
            ActionNode1_a = Group.Direction;
            ActionNode1_b = Group.Speed;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Multiply
            ActionNode1_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode1_a, ActionNode1_b);
            // SetVariableNode
            ActionNode3_Result.velocity = (UnityEngine.Vector3)ActionNode1_Result;
        }
    }
}
