// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ProjectileComponentCreated {
        
        public Projectile Group;
        
        private Projectile _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode1_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode1_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode1_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Vector3 ActionNode2_a = default( UnityEngine.Vector3 );
        
        private float ActionNode2_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode2_Result = default( UnityEngine.Vector3 );
        
        public Projectile Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode1_go = Group.Entity.gameObject;
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            while (this.DebugInfo("b79c1b46-db65-4d07-b68a-edb7a9660a30", this) == 1) yield return new WaitForEndOfFrame();
            ActionNode1_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode1_go, ActionNode1_component);
            ActionNode2_a = Group.Entity.transform.forward;
            ActionNode2_b = Group.Speed;
            // Visit uFrame.Actions.Vector3Library.Multiply
            while (this.DebugInfo("538ddc66-8110-45f1-b450-bc8c12dc63f3", this) == 1) yield return new WaitForEndOfFrame();
            ActionNode2_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode2_a, ActionNode2_b);
            ActionNode1_Result.velocity = (UnityEngine.Vector3)ActionNode2_Result;
            // HANDLER: ProjectileComponentCreated
            yield break;
        }
    }
}
