// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class ScrollSystemUpdateHandler {
        
        public BackgroundScroller Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.Vector3 ActionNode4_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 Vector3Node7 = new UnityEngine.Vector3(0f,0f,1f);
        
        private float ActionNode1_Result = default( System.Single );
        
        private float ActionNode2_a = default( System.Single );
        
        private float ActionNode2_b = default( System.Single );
        
        private float ActionNode2_Result = default( System.Single );
        
        private float ActionNode0_t = default( System.Single );
        
        private float ActionNode0_length = default( System.Single );
        
        private float ActionNode0_Result = default( System.Single );
        
        private float ActionNode4_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode4_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode3_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode3_b = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode3_Result = default( UnityEngine.Vector3 );
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode4_a = Vector3Node7;
            // ActionNode
            // Visit uFrame.Actions.TimeLibrary.GetTime
            ActionNode1_Result = uFrame.Actions.TimeLibrary.GetTime();
            ActionNode2_a = ActionNode1_Result;
            ActionNode2_b = Group.ScrollSpeed;
            // ActionNode
            // Visit uFrame.Actions.FloatLibrary.Multiply
            ActionNode2_Result = uFrame.Actions.FloatLibrary.Multiply(ActionNode2_a, ActionNode2_b);
            ActionNode0_t = ActionNode2_Result;
            ActionNode0_length = Group.TileSizeZ;
            // ActionNode
            // Visit UnityEngine.Mathf.Repeat
            ActionNode0_Result = UnityEngine.Mathf.Repeat(ActionNode0_t, ActionNode0_length);
            ActionNode4_b = ActionNode0_Result;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Multiply
            ActionNode4_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode4_a, ActionNode4_b);
            ActionNode3_a = ActionNode4_Result;
            ActionNode3_b = Group.StartPosition;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Add
            ActionNode3_Result = uFrame.Actions.Vector3Library.Add(ActionNode3_a, ActionNode3_b);
            // SetVariableNode
            Group.Entity.transform.position = (UnityEngine.Vector3)ActionNode3_Result;
        }
    }
}
