// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ScrollSystemUpdateHandler {
        
        public BackgroundScroller Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.Vector3 ActionNode8_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 Vector3Node7 = new UnityEngine.Vector3(0f,0f,1f);
        
        private float ActionNode3_Result = default( System.Single );
        
        private float ActionNode5_a = default( System.Single );
        
        private float ActionNode5_b = default( System.Single );
        
        private float ActionNode5_Result = default( System.Single );
        
        private float ActionNode4_t = default( System.Single );
        
        private float ActionNode4_length = default( System.Single );
        
        private float ActionNode4_Result = default( System.Single );
        
        private float ActionNode8_b = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode8_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode9_a = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode9_b = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode9_Result = default( UnityEngine.Vector3 );
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode8_a = Vector3Node7;
            // ActionNode
            // Visit uFrame.Actions.TimeLibrary.GetTime
            ActionNode3_Result = uFrame.Actions.TimeLibrary.GetTime();
            ActionNode5_a = ActionNode3_Result;
            ActionNode5_b = Group.ScrollSpeed;
            // ActionNode
            // Visit uFrame.Actions.FloatLibrary.Multiply
            ActionNode5_Result = uFrame.Actions.FloatLibrary.Multiply(ActionNode5_a, ActionNode5_b);
            ActionNode4_t = ActionNode5_Result;
            ActionNode4_length = Group.TileSizeZ;
            // ActionNode
            // Visit UnityEngine.Mathf.Repeat
            ActionNode4_Result = UnityEngine.Mathf.Repeat(ActionNode4_t, ActionNode4_length);
            ActionNode8_b = ActionNode4_Result;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Multiply
            ActionNode8_Result = uFrame.Actions.Vector3Library.Multiply(ActionNode8_a, ActionNode8_b);
            ActionNode9_a = ActionNode8_Result;
            ActionNode9_b = Group.StartPosition;
            // ActionNode
            // Visit uFrame.Actions.Vector3Library.Add
            ActionNode9_Result = uFrame.Actions.Vector3Library.Add(ActionNode9_a, ActionNode9_b);
            // SetVariableNode
            Group.Entity.transform.position = (UnityEngine.Vector3)ActionNode9_Result;
        }
    }
}
