// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class SpawnWithRandomXComponentCreated {
        
        public SpawnWithRandomX Group;
        
        private SpawnWithRandomX _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private float ActionNode5_minX = default( System.Single );
        
        private float ActionNode5_maxX = default( System.Single );
        
        private float ActionNode5_minY = default( System.Single );
        
        private float ActionNode5_maxY = default( System.Single );
        
        private float ActionNode5_minZ = default( System.Single );
        
        private float ActionNode5_maxZ = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode5_Result = default( UnityEngine.Vector3 );
        
        public SpawnWithRandomX Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode5_minX = Group.XRange.x;
            ActionNode5_maxX = Group.XRange.y;
            ActionNode5_minY = Group.Y;
            ActionNode5_maxY = Group.Y;
            ActionNode5_minZ = Group.Z;
            ActionNode5_maxZ = Group.Z;
            // ActionNode
            // Visit uFrame.Actions.CreateRandoms.RandomVector3
            ActionNode5_Result = uFrame.Actions.CreateRandoms.RandomVector3(ActionNode5_minX, ActionNode5_maxX, ActionNode5_minY, ActionNode5_maxY, ActionNode5_minZ, ActionNode5_maxZ);
            // SetVariableNode
            Group.Entity.transform.position = (UnityEngine.Vector3)ActionNode5_Result;
        }
    }
}
