// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class WavesGameScorePropertyChanged {
        
        public WavesGame Group;
        
        private WavesGame _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.ScoreText LoopGroupNode7_Item = default( uFrameECSDemo.ScoreText );
        
        public WavesGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // LoopGroupNode
            var LoopGroupNode7_GroupComponents = System.ComponentSystem.RegisterComponent<uFrameECSDemo.ScoreText>().Components;
            for (var LoopGroupNode7_ItemIndex = 0
            ; LoopGroupNode7_ItemIndex < LoopGroupNode7_GroupComponents.Count; LoopGroupNode7_ItemIndex++
            ) {
                LoopGroupNode7_Item = LoopGroupNode7_GroupComponents[LoopGroupNode7_ItemIndex];
                LoopGroupNode7_Next();
            }
        }
        
        private void LoopGroupNode7_Next() {
        }
    }
}
