// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ShooterFixedUpdateHandler {
        
        public Movable Group;
        
        private uFrame.ECS.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode2_axisName = default( System.String );
        
        private string StringNode3 = "Horizontal";
        
        private float ActionNode2_Result = default( System.Single );
        
        private string ActionNode4_axisName = default( System.String );
        
        private string StringNode5 = "Vertical";
        
        private float ActionNode4_Result = default( System.Single );
        
        private UnityEngine.GameObject ActionNode0_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode0_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode0_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Rigidbody ActionNode0_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode0_x = default( System.Single );
        
        private float ActionNode0_y = default( System.Single );
        
        private float ActionNode0_z = default( System.Single );
        
        private float ActionNode0_speed = default( System.Single );
        
        private UnityEngine.Rigidbody ActionNode1_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode1_x = default( System.Single );
        
        private float ActionNode1_y = default( System.Single );
        
        private float ActionNode8_a = default( System.Single );
        
        private float ActionNode8_b = default( System.Single );
        
        private float ActionNode8_result = default( System.Single );
        
        private float ActionNode1_z = default( System.Single );
        
        public uFrame.ECS.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // ActionGroupNode
            ActionNode2_axisName = StringNode3;
            // ActionNode
            // Visit UnityEngine.Input.GetAxis
            ActionNode2_Result = UnityEngine.Input.GetAxis(ActionNode2_axisName);
            // SetVariableNode
            Group.Horizontal = (System.Single)ActionNode2_Result;
            ActionNode4_axisName = StringNode5;
            // ActionNode
            // Visit UnityEngine.Input.GetAxis
            ActionNode4_Result = UnityEngine.Input.GetAxis(ActionNode4_axisName);
            // SetVariableNode
            Group.Vertical = (System.Single)ActionNode4_Result;
            ActionNode0_go = Group.Entity.gameObject;
            // ActionNode
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            ActionNode0_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode0_go, ActionNode0_component);
            ActionNode0_rigidBody = ActionNode0_Result;
            ActionNode0_x = Group.Horizontal;
            ActionNode0_z = Group.Vertical;
            ActionNode0_speed = Group.Speed;
            // ActionNode
            // Visit uFrame.Actions.RigidbodyLibrary.SetVelocityWithSpeed
            uFrame.Actions.RigidbodyLibrary.SetVelocityWithSpeed(ActionNode0_rigidBody, ActionNode0_x, ActionNode0_y, ActionNode0_z, ActionNode0_speed);
            ActionNode1_rigidBody = ActionNode0_Result;
            ActionNode8_a = ActionNode0_Result.velocity.x;
            ActionNode8_b = Group.Tilt;
            // ActionNode
            // Visit Assets.uFrameECS.Framework.Actions.MathLibrary.Multiply
            Assets.uFrameECS.Framework.Actions.MathLibrary.Multiply(ActionNode8_a, ActionNode8_b, out ActionNode8_result);
            ActionNode1_z = ActionNode8_result;
            // ActionNode
            // Visit uFrame.Actions.RigidbodyLibrary.SetRigidbodyRotation
            uFrame.Actions.RigidbodyLibrary.SetRigidbodyRotation(ActionNode1_rigidBody, ActionNode1_x, ActionNode1_y, ActionNode1_z);
        }
    }
}
