// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class ShooterFixedUpdateHandler {
        
        public Movable Group;
        
        private uFrame.ECS.ISystemFixedUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private string ActionNode2_axisName = default( System.String );
        
        private string StringNode3 = "Horizontal";
        
        private float ActionNode2_Result = default( System.Single );
        
        private string ActionNode4_axisName = default( System.String );
        
        private string StringNode5 = "Vertical";
        
        private float ActionNode4_Result = default( System.Single );
        
        private UnityEngine.GameObject ActionNode0_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode0_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode0_Result = default( UnityEngine.Rigidbody );
        
        private UnityEngine.Rigidbody ActionNode6_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode6_x = default( System.Single );
        
        private float ActionNode6_y = default( System.Single );
        
        private float ActionNode6_z = default( System.Single );
        
        private float ActionNode6_speed = default( System.Single );
        
        private UnityEngine.Rigidbody ActionNode7_rigidBody = default( UnityEngine.Rigidbody );
        
        private float ActionNode7_x = default( System.Single );
        
        private float ActionNode7_y = default( System.Single );
        
        private float ActionNode8_a = default( System.Single );
        
        private float ActionNode8_b = default( System.Single );
        
        private float ActionNode8_result = default( System.Single );
        
        private float ActionNode7_z = default( System.Single );
        
        public uFrame.ECS.ISystemFixedUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode2_axisName = StringNode3;
            // Visit UnityEngine.Input.GetAxis
            while (this.DebugInfo("8d4dde43-3481-451f-8725-34470dfab500", this) == 1) yield return new WaitForEndOfFrame();
            ActionNode2_Result = UnityEngine.Input.GetAxis(ActionNode2_axisName);
            Group.Horizontal = (System.Single)ActionNode2_Result;
            ActionNode4_axisName = StringNode5;
            // Visit UnityEngine.Input.GetAxis
            while (this.DebugInfo("73d130d8-a7ae-457e-a9b6-ff156bd38bb3", this) == 1) yield return new WaitForEndOfFrame();
            ActionNode4_Result = UnityEngine.Input.GetAxis(ActionNode4_axisName);
            Group.Vertical = (System.Single)ActionNode4_Result;
            ActionNode0_go = Group.Entity.gameObject;
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            while (this.DebugInfo("80244fdb-97b7-44b3-adb0-daea66fa82b0", this) == 1) yield return new WaitForEndOfFrame();
            ActionNode0_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode0_go, ActionNode0_component);
            ActionNode6_rigidBody = ActionNode0_Result;
            ActionNode6_x = Group.Horizontal;
            ActionNode6_z = Group.Vertical;
            ActionNode6_speed = Group.Speed;
            // Visit RigidbodyLibrary.SetVelocityWithSpeed
            while (this.DebugInfo("abe712ab-a116-4855-b9e3-ee79b3714c1b", this) == 1) yield return new WaitForEndOfFrame();
            RigidbodyLibrary.SetVelocityWithSpeed(ActionNode6_rigidBody, ActionNode6_x, ActionNode6_y, ActionNode6_z, ActionNode6_speed);
            ActionNode7_rigidBody = ActionNode0_Result;
            ActionNode8_a = ActionNode0_Result.velocity.x;
            ActionNode8_b = Group.Tilt;
            // Visit Assets.uFrameECS.Framework.Actions.MathLibrary.Multiply
            while (this.DebugInfo("978ce53c-9116-4089-809a-617d10a0d551", this) == 1) yield return new WaitForEndOfFrame();
            Assets.uFrameECS.Framework.Actions.MathLibrary.Multiply(ActionNode8_a, ActionNode8_b, out ActionNode8_result);
            ActionNode7_z = ActionNode8_result;
            // Visit RigidbodyLibrary.SetRigidbodyRotation
            while (this.DebugInfo("59f7cdc1-0e33-4c33-a7c5-63bb2bd9e8c0", this) == 1) yield return new WaitForEndOfFrame();
            RigidbodyLibrary.SetRigidbodyRotation(ActionNode7_rigidBody, ActionNode7_x, ActionNode7_y, ActionNode7_z);
            // HANDLER: ShooterFixedUpdate
            yield break;
        }
    }
}
