// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class ShootingGunsComponentCreated {
        
        public ShootingGuns Group;
        
        private ShootingGuns _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode21_message = default( System.Object );
        
        private string StringNode22 = "Success";
        
        public ShootingGuns Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode21_message = StringNode22;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            while (this.DebugInfo("","70ad0e1f-f396-4b64-97bc-ce045840c05c", this) == 1) yield return null;
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode21_message);
            // HANDLER: StartFiring
            yield break;
        }
    }
}
