// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class ShootingGunsComponentDestroyed {
        
        public ShootingGuns Group;
        
        private ShootingGuns _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode19_message = default( System.Object );
        
        private string StringNode20 = "Removed";
        
        public ShootingGuns Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode19_message = StringNode20;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            while (this.DebugInfo("0e52fecd-92b1-4be7-bfb6-9a010273790b","6afadd07-6bc7-460a-a1ec-3e7126715bda", this) == 1) yield return null;
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode19_message);
            // HANDLER: StopFiring
            yield break;
        }
    }
}
