// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class WavesGameSystemGameOverHandler {
        
        public WavesGame Group;
        
        private uFrameECSDemo.GameOver _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode27_gameObject = default( UnityEngine.GameObject );
        
        private int ActionNode42_in = default( System.Int32 );
        
        private int IntNode41 = 1;
        
        private float ActionNode42_Result = default( System.Single );
        
        private float ActionNode27_time = default( System.Single );
        
        public uFrameECSDemo.GameOver Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode27_gameObject = Group.Entity.gameObject;
            ActionNode42_in = IntNode41;
            // ActionNode
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode42_Result = uFrame.Actions.Converter.IntToFloat(ActionNode42_in);
            ActionNode27_time = ActionNode42_Result;
            // ActionNode
            // Visit uFrame.Actions.DestroyLibrary.DestroyGameObject
            uFrame.Actions.DestroyLibrary.DestroyGameObject(ActionNode27_gameObject, ActionNode27_time);
        }
    }
}
