// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class WeaponSystemGunnerFireHandler {
        
        public Gunner Group;
        
        public Gunner GunnerId;
        
        private uFrameECSDemo.GunnerFire _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private uFrameECSDemo.Gun LoopCollectionNode1_Item = default( uFrameECSDemo.Gun );
        
        private object Action0_message = default( System.Object );
        
        public uFrameECSDemo.GunnerFire Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // Loop Collection
            for (var LoopCollectionNode1_ItemIndex = 0
            ; LoopCollectionNode1_ItemIndex < Group.Guns.Count; LoopCollectionNode1_ItemIndex++
            ) {
                LoopCollectionNode1_Item = Group.Guns[LoopCollectionNode1_ItemIndex];
                LoopCollectionNode1_Next();
            }
            // HANDLER: WeaponSystemGunnerFire
            yield break;
        }
        
        private System.Collections.IEnumerator LoopCollectionNode1_Next() {
            Action0_message = LoopCollectionNode1_Item.ProjectilePrefab;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            while (this.DebugInfo("7d8aa1eb-e361-44f0-a68e-41cd78d4c5e1", this) == 1) yield return new WaitForEndOfFrame();
            uFrame.Actions.DebugLibrary.LogMessage(Action0_message);
            yield break;
        }
    }
}
