// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UnityEngine;
    using uFrame.ECS;
    
    
    public class WeaponSystemUpdateHandler {
        
        public ShootingGuns Group;
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private float ActionNode10_Result = default( System.Single );
        
        private float ActionNode15_a = default( System.Single );
        
        private float ActionNode15_b = default( System.Single );
        
        private bool ActionNode15_Result = default( System.Boolean );
        
        private float ActionNode13_a = default( System.Single );
        
        private float ActionNode13_b = default( System.Single );
        
        private float ActionNode13_Result = default( System.Single );
        
        private string ActionNode9_PoolName = default( System.String );
        
        private string ActionNode9_PrefabName = default( System.String );
        
        private UnityEngine.Vector3 ActionNode9_Position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode9_Rotation = default( UnityEngine.Vector3 );
        
        private uFrame.ECS.Spawn ActionNode9 = new uFrame.ECS.Spawn();
        
        private uFrame.ECS.Entity ActionNode9_Result = default( uFrame.ECS.Entity );
        
        private UnityEngine.GameObject ActionNode26_gameObject = default( UnityEngine.GameObject );
        
        private float ActionNode26_time = default( System.Single );
        
        private float FloatNode27 = 3F;
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // ActionNode
            // Visit uFrame.Actions.TimeLibrary.GetTime
            ActionNode10_Result = uFrame.Actions.TimeLibrary.GetTime();
            ActionNode15_a = ActionNode10_Result;
            ActionNode15_b = Group.Gun.NextFire;
            // ActionNode
            // Visit uFrame.Actions.Comparisons.GreaterThan
            ActionNode15_Result = uFrame.Actions.Comparisons.GreaterThan(ActionNode15_a, ActionNode15_b, ActionNode15_yes, ActionNode15_no);
        }
        
        private void ActionNode15_yes() {
            ActionNode13_a = ActionNode10_Result;
            ActionNode13_b = Group.Gun.FireRate;
            // ActionNode
            // Visit uFrame.Actions.FloatLibrary.Add
            ActionNode13_Result = uFrame.Actions.FloatLibrary.Add(ActionNode13_a, ActionNode13_b);
            // SetVariableNode
            Group.Gun.NextFire = (System.Single)ActionNode13_Result;
            ActionNode9_PoolName = Group.Gun.ProjectilePrefab;
            ActionNode9_Position = Group.Entity.transform.position;
            // ActionNode
            // Visit uFrame.ECS.Spawn
            ActionNode9.PoolName = ActionNode9_PoolName;
            ActionNode9.Position = ActionNode9_Position;
            ActionNode9.System = System;
            ActionNode9.Execute();
            ActionNode9_Result = ActionNode9.Result;
            ActionNode26_gameObject = ActionNode9_Result.gameObject;
            ActionNode26_time = FloatNode27;
            // ActionNode
            // Visit uFrame.Actions.DestroyLibrary.DestroyGameObject
            uFrame.Actions.DestroyLibrary.DestroyGameObject(ActionNode26_gameObject, ActionNode26_time);
        }
        
        private void ActionNode15_no() {
        }
    }
}
