// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class NewHandlerNodeHandler {
        
        private uFrameECSDemo.SpawnEnemy _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        public uFrameECSDemo.SpawnEnemy Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // HANDLER: NewHandlerNode
            yield break;
        }
    }
    
    public class GameStartedHandler {
        
        public GameSettings Group;
        
        private uFrameECSDemo.PlayGame _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int Interval_Minutes = default( System.Int32 );
        
        private int Interval_Seconds = default( System.Int32 );
        
        private uFrame.Actions.Interval baaeeeabdcd = new uFrame.Actions.Interval();
        
        private System.IDisposable Interval_Result = default( System.IDisposable );
        
        public uFrameECSDemo.PlayGame Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // Before visit uFrame.Actions.Interval
            // Visit uFrame.Actions.Interval
            baaeeeabdcd.System = System;
            while (this.DebugInfo("863b189a-0ae2-473e-8eab-935d6321c6d8", this) == 1) yield return new WaitForEndOfFrame();
            baaeeeabdcd.Execute();
            Interval_Result = baaeeeabdcd.Result;
            // Visit Output
            // HANDLER: GameStarted
            yield break;
        }
        
        private System.Collections.IEnumerator Interval_Tick() {
            Interval_Result = baaeeeabdcd.Result;
            yield break;
        }
    }
}
