// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.uFrameIdentifier("55bd0141-748d-490e-9c53-d5c9ec95b58d")]
    public partial class EnemyAISystem : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemFixedUpdate {
        
        private IEcsComponentManagerOf<EnemyAI> _EnemyAIManager;
        
        private IEcsComponentManagerOf<RandomRotation> _RandomRotationManager;
        
        private IEcsComponentManagerOf<Projectile> _ProjectileManager;
        
        private IEcsComponentManagerOf<SpawnWithRandomX> _SpawnWithRandomXManager;
        
        private IEcsComponentManagerOf<DestroyOnCollision> _DestroyOnCollisionManager;
        
        private EnemyAISystemFixedUpdateHandler EnemyAISystemFixedUpdateHandlerInstance = new EnemyAISystemFixedUpdateHandler();
        
        private EnemyAICreatedComponentCreated EnemyAICreatedComponentCreatedInstance = new EnemyAICreatedComponentCreated();
        
        public IEcsComponentManagerOf<EnemyAI> EnemyAIManager {
            get {
                return _EnemyAIManager;
            }
            set {
                _EnemyAIManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RandomRotation> RandomRotationManager {
            get {
                return _RandomRotationManager;
            }
            set {
                _RandomRotationManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Projectile> ProjectileManager {
            get {
                return _ProjectileManager;
            }
            set {
                _ProjectileManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SpawnWithRandomX> SpawnWithRandomXManager {
            get {
                return _SpawnWithRandomXManager;
            }
            set {
                _SpawnWithRandomXManager = value;
            }
        }
        
        public IEcsComponentManagerOf<DestroyOnCollision> DestroyOnCollisionManager {
            get {
                return _DestroyOnCollisionManager;
            }
            set {
                _DestroyOnCollisionManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            EnemyAIManager = ComponentSystem.RegisterComponent<EnemyAI>();
            RandomRotationManager = ComponentSystem.RegisterComponent<RandomRotation>();
            ProjectileManager = ComponentSystem.RegisterComponent<Projectile>();
            SpawnWithRandomXManager = ComponentSystem.RegisterComponent<SpawnWithRandomX>();
            DestroyOnCollisionManager = ComponentSystem.RegisterComponent<DestroyOnCollision>();
            EnemyAIManager.CreatedObservable.Subscribe(EnemyAICreatedComponentCreatedFilter).DisposeWith(this);
        }
        
        protected void EnemyAISystemFixedUpdateHandler(EnemyAI group) {
            var handler = EnemyAISystemFixedUpdateHandlerInstance;;
            handler.System = this;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void EnemyAISystemFixedUpdateFilter() {
            var EnemyAIItems = EnemyAIManager.Components;
            for (var EnemyAIIndex = 0
            ; EnemyAIIndex < EnemyAIItems.Count; EnemyAIIndex++
            ) {
                this.EnemyAISystemFixedUpdateHandler(EnemyAIItems[EnemyAIIndex]);
            }
        }
        
        public virtual void SystemFixedUpdate() {
            EnemyAISystemFixedUpdateFilter();
        }
        
        protected void EnemyAICreatedComponentCreated(EnemyAI data, EnemyAI group) {
            var handler = EnemyAICreatedComponentCreatedInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void EnemyAICreatedComponentCreatedFilter(EnemyAI data) {
            var GroupEnemyAI = EnemyAIManager[data.EntityId];
            if (GroupEnemyAI == null) {
                return;
            }
            this.EnemyAICreatedComponentCreated(data, GroupEnemyAI);
        }
    }
}
