// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrameECSDemo;
    using UnityEngine;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UniRx;
    
    
    public partial class EnemyAISystemBase : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemFixedUpdate {
        
        private IEcsComponentManagerOf<EnemyAI> _EnemyAIManager;
        
        private IEcsComponentManagerOf<RandomRotation> _RandomRotationManager;
        
        private IEcsComponentManagerOf<Projectile> _ProjectileManager;
        
        private IEcsComponentManagerOf<SpawnWithRandomX> _SpawnWithRandomXManager;
        
        private IEcsComponentManagerOf<DestroyOnCollision> _DestroyOnCollisionManager;
        
        private IEcsComponentManagerOf<Hazard> _HazardManager;
        
        public IEcsComponentManagerOf<EnemyAI> EnemyAIManager {
            get {
                return _EnemyAIManager;
            }
            set {
                _EnemyAIManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RandomRotation> RandomRotationManager {
            get {
                return _RandomRotationManager;
            }
            set {
                _RandomRotationManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Projectile> ProjectileManager {
            get {
                return _ProjectileManager;
            }
            set {
                _ProjectileManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SpawnWithRandomX> SpawnWithRandomXManager {
            get {
                return _SpawnWithRandomXManager;
            }
            set {
                _SpawnWithRandomXManager = value;
            }
        }
        
        public IEcsComponentManagerOf<DestroyOnCollision> DestroyOnCollisionManager {
            get {
                return _DestroyOnCollisionManager;
            }
            set {
                _DestroyOnCollisionManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Hazard> HazardManager {
            get {
                return _HazardManager;
            }
            set {
                _HazardManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            EnemyAIManager = ComponentSystem.RegisterComponent<EnemyAI>(89);
            RandomRotationManager = ComponentSystem.RegisterComponent<RandomRotation>(91);
            ProjectileManager = ComponentSystem.RegisterComponent<Projectile>(90);
            SpawnWithRandomXManager = ComponentSystem.RegisterComponent<SpawnWithRandomX>(92);
            DestroyOnCollisionManager = ComponentSystem.RegisterComponent<DestroyOnCollision>(88);
            HazardManager = ComponentSystem.RegisterComponent<Hazard>(87);
            EnemyAIManager.CreatedObservable.Subscribe(EnemyAICreatedFilter).DisposeWith(this);
            this.OnEvent<uFrame.ECS.OnCollisionEnterDispatcher>().Subscribe(_=>{ EnemyAISystemOnCollisionEnterFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void EnemyAISystemFixedUpdateHandler(EnemyAI group) {
            var handler = new EnemyAISystemFixedUpdateHandler();
            handler.System = this;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void EnemyAISystemFixedUpdateFilter() {
            var EnemyAIItems = EnemyAIManager.Components;
            for (var EnemyAIIndex = 0
            ; EnemyAIIndex < EnemyAIItems.Count; EnemyAIIndex++
            ) {
                if (!EnemyAIItems[EnemyAIIndex].Enabled) {
                    continue;
                }
                this.EnemyAISystemFixedUpdateHandler(EnemyAIItems[EnemyAIIndex]);
            }
        }
        
        public virtual void SystemFixedUpdate() {
            EnemyAISystemFixedUpdateFilter();
        }
        
        protected virtual void EnemyAICreated(EnemyAI data, EnemyAI group) {
            var handler = new EnemyAICreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void EnemyAICreatedFilter(EnemyAI data) {
            var GroupEnemyAI = EnemyAIManager[data.EntityId];
            if (GroupEnemyAI == null) {
                return;
            }
            if (!GroupEnemyAI.Enabled) {
                return;
            }
            this.EnemyAICreated(data, GroupEnemyAI);
        }
        
        protected virtual void EnemyAISystemOnCollisionEnterHandler(uFrame.ECS.OnCollisionEnterDispatcher data) {
            var handler = new EnemyAISystemOnCollisionEnterHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void EnemyAISystemOnCollisionEnterFilter(uFrame.ECS.OnCollisionEnterDispatcher data) {
            this.EnemyAISystemOnCollisionEnterHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("55bd0141-748d-490e-9c53-d5c9ec95b58d")]
    public partial class EnemyAISystem : EnemyAISystemBase {
        
        private static EnemyAISystem _Instance;
        
        public EnemyAISystem() {
            Instance = this;
        }
        
        public static EnemyAISystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
