// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public partial class Movement : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<Projectile> _ProjectileManager;
        
        public IEcsComponentManagerOf<Projectile> ProjectileManager {
            get {
                return _ProjectileManager;
            }
            set {
                _ProjectileManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            ProjectileManager = ComponentSystem.RegisterComponent<Projectile>();
            ProjectileManager.CreatedObservable.Subscribe(ProjectileComponentCreatedFilter).DisposeWith(this);
        }
        
        protected void ProjectileComponentCreated(Projectile data, Projectile group) {
            var handler = new ProjectileComponentCreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void ProjectileComponentCreatedFilter(Projectile data) {
            var GroupProjectile = ProjectileManager[data.EntityId];
            if (GroupProjectile == null) {
                return;
            }
            this.ProjectileComponentCreated(data, GroupProjectile);
        }
    }
}
