// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    #region 
static
    public class PlayerModuleExtensions {
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<Movable> MovableManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Movable>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<PlayerGunner> PlayerGunnerManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<PlayerGunner>();
        }
        #endregion
        
        #region 
static
        public List<Movable> MovableComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<Movable>().Components;
        }
        #endregion
        
        #region 
static
        public List<PlayerGunner> PlayerGunnerComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<PlayerGunner>().Components;
        }
        #endregion
    }
    #endregion
}
