// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrameECSDemo;
    using UnityEngine;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("539cad18-5a60-40ba-b2c3-51f2d670f0e5")]
    public partial class PlayerMovementSystem : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemFixedUpdate {
        
        private static PlayerMovementSystem _Instance;
        
        private IEcsComponentManagerOf<PlayerGunner> _PlayerGunnerManager;
        
        private IEcsComponentManagerOf<Movable> _MovableManager;
        
        private IEcsComponentManagerOf<Hazard> _HazardManager;
        
        private IEcsComponentManagerOf<WavesGame> _WavesGameManager;
        
        private IEcsComponentManagerOf<Player> _PlayerManager;
        
        public static PlayerMovementSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public IEcsComponentManagerOf<PlayerGunner> PlayerGunnerManager {
            get {
                return _PlayerGunnerManager;
            }
            set {
                _PlayerGunnerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Movable> MovableManager {
            get {
                return _MovableManager;
            }
            set {
                _MovableManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Hazard> HazardManager {
            get {
                return _HazardManager;
            }
            set {
                _HazardManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WavesGame> WavesGameManager {
            get {
                return _WavesGameManager;
            }
            set {
                _WavesGameManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Player> PlayerManager {
            get {
                return _PlayerManager;
            }
            set {
                _PlayerManager = value;
            }
        }
        
        public override void Setup() {
            Instance = this;
            base.Setup();
            PlayerGunnerManager = ComponentSystem.RegisterGroup<PlayerGunnerGroup,PlayerGunner>();
            MovableManager = ComponentSystem.RegisterComponent<Movable>(25);
            HazardManager = ComponentSystem.RegisterComponent<Hazard>(81);
            WavesGameManager = ComponentSystem.RegisterComponent<WavesGame>(8);
            PlayerManager = ComponentSystem.RegisterComponent<Player>(23);
        }
        
        protected void ShooterFixedUpdateHandler(Movable group) {
            var handler = new ShooterFixedUpdateHandler();
            handler.System = this;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void ShooterFixedUpdateFilter() {
            var MovableItems = MovableManager.Components;
            for (var MovableIndex = 0
            ; MovableIndex < MovableItems.Count; MovableIndex++
            ) {
                if (!MovableItems[MovableIndex].Enabled) {
                    continue;
                }
                this.ShooterFixedUpdateHandler(MovableItems[MovableIndex]);
            }
        }
        
        public virtual void SystemFixedUpdate() {
            ShooterFixedUpdateFilter();
        }
    }
}
