// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("c39f72a9-03fa-4cc0-990c-f82be2aa6954")]
    public partial class ScrollSystem : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemUpdate {
        
        private IEcsComponentManagerOf<BackgroundScroller> _BackgroundScrollerManager;
        
        private ScrollSystemUpdateHandler ScrollSystemUpdateHandlerInstance = new ScrollSystemUpdateHandler();
        
        private BackgroundScrollerComponentCreated BackgroundScrollerComponentCreatedInstance = new BackgroundScrollerComponentCreated();
        
        public IEcsComponentManagerOf<BackgroundScroller> BackgroundScrollerManager {
            get {
                return _BackgroundScrollerManager;
            }
            set {
                _BackgroundScrollerManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            BackgroundScrollerManager = ComponentSystem.RegisterComponent<BackgroundScroller>();
            BackgroundScrollerManager.CreatedObservable.Subscribe(BackgroundScrollerComponentCreatedFilter).DisposeWith(this);
        }
        
        protected void ScrollSystemUpdateHandler(BackgroundScroller group) {
            var handler = ScrollSystemUpdateHandlerInstance;;
            handler.System = this;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void ScrollSystemUpdateFilter() {
            var BackgroundScrollerItems = BackgroundScrollerManager.Components;
            for (var BackgroundScrollerIndex = 0
            ; BackgroundScrollerIndex < BackgroundScrollerItems.Count; BackgroundScrollerIndex++
            ) {
                this.ScrollSystemUpdateHandler(BackgroundScrollerItems[BackgroundScrollerIndex]);
            }
        }
        
        public virtual void SystemUpdate() {
            ScrollSystemUpdateFilter();
        }
        
        protected void BackgroundScrollerComponentCreated(BackgroundScroller data, BackgroundScroller group) {
            var handler = BackgroundScrollerComponentCreatedInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void BackgroundScrollerComponentCreatedFilter(BackgroundScroller data) {
            var GroupBackgroundScroller = BackgroundScrollerManager[data.EntityId];
            if (GroupBackgroundScroller == null) {
                return;
            }
            this.BackgroundScrollerComponentCreated(data, GroupBackgroundScroller);
        }
    }
}
