// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [uFrame.Attributes.uFrameIdentifier("a3b30320-253b-43b5-b2c2-0701d6370261")]
    public partial class Shooter : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemFixedUpdate {
        
        private IEcsComponentManagerOf<Movable> _MovableManager;
        
        public IEcsComponentManagerOf<Movable> MovableManager {
            get {
                return _MovableManager;
            }
            set {
                _MovableManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MovableManager = ComponentSystem.RegisterComponent<Movable>();
        }
        
        protected void ShooterFixedUpdateHandler(Movable group) {
            var handler = new ShooterFixedUpdateHandler();
            handler.System = this;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void ShooterFixedUpdateFilter() {
            var MovableItems = MovableManager.Components;
            for (var MovableIndex = 0
            ; MovableIndex < MovableItems.Count; MovableIndex++
            ) {
                this.ShooterFixedUpdateHandler(MovableItems[MovableIndex]);
            }
        }
        
        public virtual void SystemFixedUpdate() {
            ShooterFixedUpdateFilter();
        }
    }
}
