// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public partial class SoundSystem : uFrame.ECS.EcsSystem {
        
        public override void Setup() {
            base.Setup();
            this.OnEvent<uFrameECSDemo.GameOver>().Subscribe(_=>{ SoundSystemGameOverFilter(_); }).DisposeWith(this);
        }
        
        protected void SoundSystemGameOverHandler(uFrameECSDemo.GameOver data) {
            var handler = new SoundSystemGameOverHandler();
            handler.System = this;
            handler.Event = data;
            StartCoroutine(handler.Execute());
        }
        
        protected void SoundSystemGameOverFilter(uFrameECSDemo.GameOver data) {
            this.SoundSystemGameOverHandler(data);
        }
    }
}
