// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using uFrame.Kernel;
    using uFrameECSDemo;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("b60e9496-5928-483d-b9ee-4e5ae99f0445")]
    public partial class UISystem : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<SpawnAtInterval> _SpawnAtIntervalManager;
        
        private IEcsComponentManagerOf<WavesGame> _WavesGameManager;
        
        private IEcsComponentManagerOf<SpawnMultipleAtInterval> _SpawnMultipleAtIntervalManager;
        
        private IEcsComponentManagerOf<PointsOnDestroy> _PointsOnDestroyManager;
        
        private IEcsComponentManagerOf<PlayGameButton> _PlayGameButtonManager;
        
        private IEcsComponentManagerOf<GameOverOnCollision> _GameOverOnCollisionManager;
        
        private IEcsComponentManagerOf<ScoreText> _ScoreTextManager;
        
        private IEcsComponentManagerOf<MenuUI> _MenuUIManager;
        
        private SetScoreLabel SetScoreLabelInstance = new SetScoreLabel();
        
        private WavesGameComponentDestroyed WavesGameComponentDestroyedInstance = new WavesGameComponentDestroyed();
        
        private UISystemPointerClickDispatcherHandler UISystemPointerClickDispatcherHandlerInstance = new UISystemPointerClickDispatcherHandler();
        
        private DisableUIComponentCreated DisableUIComponentCreatedInstance = new DisableUIComponentCreated();
        
        public IEcsComponentManagerOf<SpawnAtInterval> SpawnAtIntervalManager {
            get {
                return _SpawnAtIntervalManager;
            }
            set {
                _SpawnAtIntervalManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WavesGame> WavesGameManager {
            get {
                return _WavesGameManager;
            }
            set {
                _WavesGameManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SpawnMultipleAtInterval> SpawnMultipleAtIntervalManager {
            get {
                return _SpawnMultipleAtIntervalManager;
            }
            set {
                _SpawnMultipleAtIntervalManager = value;
            }
        }
        
        public IEcsComponentManagerOf<PointsOnDestroy> PointsOnDestroyManager {
            get {
                return _PointsOnDestroyManager;
            }
            set {
                _PointsOnDestroyManager = value;
            }
        }
        
        public IEcsComponentManagerOf<PlayGameButton> PlayGameButtonManager {
            get {
                return _PlayGameButtonManager;
            }
            set {
                _PlayGameButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GameOverOnCollision> GameOverOnCollisionManager {
            get {
                return _GameOverOnCollisionManager;
            }
            set {
                _GameOverOnCollisionManager = value;
            }
        }
        
        public IEcsComponentManagerOf<ScoreText> ScoreTextManager {
            get {
                return _ScoreTextManager;
            }
            set {
                _ScoreTextManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuUI> MenuUIManager {
            get {
                return _MenuUIManager;
            }
            set {
                _MenuUIManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            SpawnAtIntervalManager = ComponentSystem.RegisterComponent<SpawnAtInterval>();
            WavesGameManager = ComponentSystem.RegisterComponent<WavesGame>();
            SpawnMultipleAtIntervalManager = ComponentSystem.RegisterComponent<SpawnMultipleAtInterval>();
            PointsOnDestroyManager = ComponentSystem.RegisterComponent<PointsOnDestroy>();
            PlayGameButtonManager = ComponentSystem.RegisterComponent<PlayGameButton>();
            GameOverOnCollisionManager = ComponentSystem.RegisterComponent<GameOverOnCollision>();
            ScoreTextManager = ComponentSystem.RegisterComponent<ScoreText>();
            MenuUIManager = ComponentSystem.RegisterComponent<MenuUI>();
            this.PropertyChangedEvent<WavesGame,System.Int32>(Group=>Group.ScoreObservable, SetScoreLabelFilter, Group=>Group.Score, false);
            WavesGameManager.RemovedObservable.Subscribe(_=>WavesGameComponentDestroyed(_,_)).DisposeWith(this);
            this.OnEvent<uFrame.ECS.PointerClickDispatcher>().Subscribe(_=>{ UISystemPointerClickDispatcherFilter(_); }).DisposeWith(this);
            WavesGameManager.CreatedObservable.Subscribe(DisableUIComponentCreatedFilter).DisposeWith(this);
        }
        
        protected void SetScoreLabel(WavesGame data, WavesGame group, PropertyChangedEvent<System.Int32> value) {
            var handler = SetScoreLabelInstance;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.OldValue = value.PreviousValue;
            handler.NewValue = value.CurrentValue;
            StartCoroutine(handler.Execute());
        }
        
        protected void SetScoreLabelFilter(WavesGame data, PropertyChangedEvent<System.Int32> value) {
            var GroupWavesGame = WavesGameManager[data.EntityId];
            if (GroupWavesGame == null) {
                return;
            }
            if (!GroupWavesGame.Enabled) {
                return;
            }
            this.SetScoreLabel(data, GroupWavesGame, value);
        }
        
        protected void WavesGameComponentDestroyed(WavesGame data, WavesGame group) {
            var handler = WavesGameComponentDestroyedInstance;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void WavesGameComponentDestroyedFilter(WavesGame data) {
            var GroupWavesGame = WavesGameManager[data.EntityId];
            if (GroupWavesGame == null) {
                return;
            }
            if (!GroupWavesGame.Enabled) {
                return;
            }
            this.WavesGameComponentDestroyed(data, GroupWavesGame);
        }
        
        protected void UISystemPointerClickDispatcherHandler(uFrame.ECS.PointerClickDispatcher data, PlayGameButton source) {
            var handler = UISystemPointerClickDispatcherHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Source = source;
            StartCoroutine(handler.Execute());
        }
        
        protected void UISystemPointerClickDispatcherFilter(uFrame.ECS.PointerClickDispatcher data) {
            var SourcePlayGameButton = PlayGameButtonManager[data.EntityId];
            if (SourcePlayGameButton == null) {
                return;
            }
            if (!SourcePlayGameButton.Enabled) {
                return;
            }
            this.UISystemPointerClickDispatcherHandler(data, SourcePlayGameButton);
        }
        
        protected void DisableUIComponentCreated(WavesGame data, WavesGame group) {
            var handler = DisableUIComponentCreatedInstance;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void DisableUIComponentCreatedFilter(WavesGame data) {
            var GroupWavesGame = WavesGameManager[data.EntityId];
            if (GroupWavesGame == null) {
                return;
            }
            if (!GroupWavesGame.Enabled) {
                return;
            }
            this.DisableUIComponentCreated(data, GroupWavesGame);
        }
    }
}
