// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    
    
    public partial class AwesomeEvent : object {
        
        [UnityEngine.SerializeField()]
        private Int32 _EntityId;
        
        public Int32 EntityId {
            get {
                return _EntityId;
            }
            set {
                _EntityId = value;
            }
        }
    }
}
