// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UniRx;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.uFrameIdentifier("b8b7185d-e28c-4185-a5e7-cddac0b0d7f4")]
    public partial class EffectOnDestroy : uFrame.ECS.EcsComponent {
        
        private Subject<GameObject> _PrefabObservable;
        
        [UnityEngine.SerializeField()]
        private GameObject _Prefab;
        
        public int ComponentID {
            get {
                return 13;
            }
        }
        
        public IObservable<GameObject> PrefabObservable {
            get {
                if (_PrefabObservable == null) {
                    _PrefabObservable = new Subject<GameObject>();
                }
                return _PrefabObservable;
            }
        }
        
        public GameObject Prefab {
            get {
                return _Prefab;
            }
            set {
                _Prefab = value;
                if (_PrefabObservable != null) {
                    _PrefabObservable.OnNext(value);
                }
            }
        }
    }
}
