// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("0905b2df-22a8-4221-8111-7d1ab8872b9a")]
    public partial class GameOverOnCollision : uFrame.ECS.EcsComponent {
        
        public int ComponentID {
            get {
                return 21;
            }
        }
    }
}
