// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UnityEngine;
    using UniRx;
    using Invert.Json;
    
    
    [uFrame.Attributes.ComponentId(23)]
    [uFrame.Attributes.uFrameIdentifier("01446f02-5f2f-4827-a3e1-9112f282e302")]
    public partial class Player : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _BestScore;
        
        private Subject<PropertyChangedEvent<Int32>> _BestScoreObservable;
        
        private PropertyChangedEvent<Int32> _BestScoreEvent;
        
        public override int ComponentId {
            get {
                return 23;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> BestScoreObservable {
            get {
                return _BestScoreObservable ?? (_BestScoreObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 BestScore {
            get {
                return _BestScore;
            }
            set {
                SetBestScore(value);
            }
        }
        
        public virtual void SetBestScore(Int32 value) {
            SetProperty(ref _BestScore, value, ref _BestScoreEvent, _BestScoreObservable);
        }
    }
}
