// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("bf206805-1753-4312-b96a-cd6dba9d62e5")]
    public partial class PlayGameButton : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private List<GameObject> _InstantiateItems;
        
        public int ComponentID {
            get {
                return 15;
            }
        }
        
        public List<GameObject> InstantiateItems {
            get {
                if (_InstantiateItems == null) {
                    _InstantiateItems = new List<GameObject>();
                }
                return _InstantiateItems;
            }
            set {
                _InstantiateItems = value;
            }
        }
    }
}
