// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UniRx;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.uFrameIdentifier("2a307e59-d342-4b51-98dc-3fe3c252eabc")]
    public partial class PointsOnDestroy : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _Points;
        
        private Subject<PropertyChangedEvent<Int32>> _PointsObservable;
        
        private PropertyChangedEvent<Int32> _PointsEvent;
        
        public int ComponentID {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> PointsObservable {
            get {
                return _PointsObservable ?? (_PointsObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 Points {
            get {
                return _Points;
            }
            set {
                SetPoints(value);
            }
        }
        
        public virtual void SetPoints(Int32 value) {
            SetProperty(ref _Points, value, ref _PointsEvent, _PointsObservable);
        }
    }
}
