// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.uFrameIdentifier("bab9f7b3-b229-4610-a916-dcd5eaf7eeb0")]
    public partial class RandomRotation : uFrame.ECS.EcsComponent {
        
        private Subject<Single> _TumbleObservable;
        
        [UnityEngine.SerializeField()]
        private Single _Tumble;
        
        public int ComponentID {
            get {
                return 17;
            }
        }
        
        public IObservable<Single> TumbleObservable {
            get {
                if (_TumbleObservable == null) {
                    _TumbleObservable = new Subject<Single>();
                }
                return _TumbleObservable;
            }
        }
        
        public Single Tumble {
            get {
                return _Tumble;
            }
            set {
                _Tumble = value;
                if (_TumbleObservable != null) {
                    _TumbleObservable.OnNext(value);
                }
            }
        }
    }
}
