// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UniRx;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.uFrameIdentifier("bab9f7b3-b229-4610-a916-dcd5eaf7eeb0")]
    public partial class RandomRotation : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Single _Tumble;
        
        private Subject<PropertyChangedEvent<Single>> _TumbleObservable;
        
        private PropertyChangedEvent<Single> _TumbleEvent;
        
        public int ComponentID {
            get {
                return 18;
            }
        }
        
        public IObservable<PropertyChangedEvent<Single>> TumbleObservable {
            get {
                return _TumbleObservable ?? (_TumbleObservable = new Subject<PropertyChangedEvent<Single>>());
            }
        }
        
        public Single Tumble {
            get {
                return _Tumble;
            }
            set {
                SetTumble(value);
            }
        }
        
        public virtual void SetTumble(Single value) {
            SetProperty(ref _Tumble, value, ref _TumbleEvent, _TumbleObservable);
        }
    }
}
