// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrameECSDemo {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("f1355431-0026-4903-8a1a-c80b46b0f183")]
    public partial class SpawnAtInterval : uFrame.ECS.EcsComponent {
        
        private Subject<System.Single> _SpeedObservable;
        
        private Subject<UnityEngine.GameObject> _PrefabObservable;
        
        private Subject<UnityEngine.Transform> _ParentObservable;
        
        [UnityEngine.SerializeField()]
        private float _Speed;
        
        [UnityEngine.SerializeField()]
        private UnityEngine.GameObject _Prefab;
        
        [UnityEngine.SerializeField()]
        private UnityEngine.Transform _Parent;
        
        public int ComponentID {
            get {
                return 23;
            }
        }
        
        public IObservable<System.Single> SpeedObservable {
            get {
                if (_SpeedObservable == null) {
                    _SpeedObservable = new Subject<System.Single>();
                }
                return _SpeedObservable;
            }
        }
        
        public IObservable<UnityEngine.GameObject> PrefabObservable {
            get {
                if (_PrefabObservable == null) {
                    _PrefabObservable = new Subject<UnityEngine.GameObject>();
                }
                return _PrefabObservable;
            }
        }
        
        public IObservable<UnityEngine.Transform> ParentObservable {
            get {
                if (_ParentObservable == null) {
                    _ParentObservable = new Subject<UnityEngine.Transform>();
                }
                return _ParentObservable;
            }
        }
        
        public float Speed {
            get {
                return _Speed;
            }
            set {
                _Speed = value;
                if (_SpeedObservable != null) {
                    _SpeedObservable.OnNext(value);
                }
            }
        }
        
        public UnityEngine.GameObject Prefab {
            get {
                return _Prefab;
            }
            set {
                _Prefab = value;
                if (_PrefabObservable != null) {
                    _PrefabObservable.OnNext(value);
                }
            }
        }
        
        public UnityEngine.Transform Parent {
            get {
                return _Parent;
            }
            set {
                _Parent = value;
                if (_ParentObservable != null) {
                    _ParentObservable.OnNext(value);
                }
            }
        }
    }
}
